language: node_js
dist: trusty
node_js:
- node
addons:
  chrome: stable
  browserstack:
    username: xuexb1
    access_key:
      secure: J/w5BzoliBGi0g+FsHBmn+aXYk1Q1YOXIECVrKt0ZJGusdN4GNaAS1oAG3Jc53BHa2CsCpCLtk06q21OXNPWADEwYmmbffNlJeQwYniJp4yHSanRg42UiPWhZ/7cWZGHdQGURHv8Np7B4n0wxThGJvk2gZiGwCKbXVeeGXK93NDaqamjKPqBojmeZQz05IvVC9H0xqwaePGyiHp+KASqZfEi2wIHiHLI64/fcJ+KcVVHA/+CmIGHytASOk9KPco+hTbnL/cgMv+HSu9ghP6TSsfXp5FTeLRplOjQ5Sljqstp6mRtRBXxbE1Ajy+H297qYixnfyVo9BC3bZFSkS3+nJAdImIB7HSKxmjGkBmhIdBBBym8/APSLPvalGaPTZjVqEbxcpEKkx4jQVXEPhefxAmRFrEXwS6VATScRlRNoloUrpXQV7sQ8GZWhVjUCYXf6CLcRCOagEL6uPZ3gW99Dpk5fhzGpcc01vR+Aq8g7xvUUnI4kKgknAUgDlviXOqYGORQPqs2WUCURFBrkyfKWUsIm7GRo2Wxif4S+t5sJJT3J/Qu96IB62ArEZZ0KhfTkHDqPp8+LbVGlklHtXtYYU0kpROO4b7JfzJNOBtGSL2p6ROyYBdjaZztvgW1QO/LKGxAMvXfWyERyahwnEclPULz23LV0FFM9nSU9tsJeT0=
env:
  global:
  - BROWSER_STACK_USERNAME: xuexb1
  - secure: qy4f4qYy0wXTYghcjlek+L5WHo4xSWvt9DQ4oJBfmRQaSo+5KalxpV7k9YfL1T0PJY6OfA1IlETPor34W60ZEtIAp+976uk62/FKUMYL77jq98Q4n3ZQVFieARg+Gsh3fCPJte7iEcv2SnR6IKlM2Y9QyPNj+So3Rfq6aDvB4aQ9wgla5ymMGE/Bk0muH5GIKQKdZ4QptvWjxNtEDPLnGQvK/EYyr5RGsAZm+U+eaA/hNl3e6MMUnTxlHfa79M1FrI4xQhzCDPIK6Kmg8mpYAefTNJl28dOhLMLC4bSgQT0hndXUuBnIAXlhZf+88ifiT91BJTYB52KH/l8NdwOG2VlW7QPR+IvTiGSIT1qkb7BTBA8PCszX8ysKvgBRlXIjwFhE7oeRjzuS9e/M9ziI70Ti1FvqU4IbkBR5OHgYZDSO8DTRpymzA1dO5ezIdoRiaPGA4wihVkqQN2nXftNO/ntBUOyjHCLXugpxcCbDniQ9HFhN4vnU3bAkuKGBK00+QI44F6ZAjAbr1Td3XGlMTPJIBeXOK9IhRygKDSuMHtMS7iZRP7EV/8dq0TT4T/kDj1OiTnm49PFGFgwJpQK/R+OqvnVOGcqKhe0OE37Oy6PC9bcIyxXi2wcg9LnWVe3gUT1QIufAF/JAvn8zO95VWdAwPfhToUC7UfDJweSatJ4=
sudo: false
cache:
  directories: node_modules
script:
- npm run test:cov
- npm run test:sauce
after_script: npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
