language: node_js
dist: trusty
node_js:
- node
addons:
  chrome: stable
  browserstack:
    username: xuexb1
    access_key:
      secure: J/w5BzoliBGi0g+FsHBmn+aXYk1Q1YOXIECVrKt0ZJGusdN4GNaAS1oAG3Jc53BHa2CsCpCLtk06q21OXNPWADEwYmmbffNlJeQwYniJp4yHSanRg42UiPWhZ/7cWZGHdQGURHv8Np7B4n0wxThGJvk2gZiGwCKbXVeeGXK93NDaqamjKPqBojmeZQz05IvVC9H0xqwaePGyiHp+KASqZfEi2wIHiHLI64/fcJ+KcVVHA/+CmIGHytASOk9KPco+hTbnL/cgMv+HSu9ghP6TSsfXp5FTeLRplOjQ5Sljqstp6mRtRBXxbE1Ajy+H297qYixnfyVo9BC3bZFSkS3+nJAdImIB7HSKxmjGkBmhIdBBBym8/APSLPvalGaPTZjVqEbxcpEKkx4jQVXEPhefxAmRFrEXwS6VATScRlRNoloUrpXQV7sQ8GZWhVjUCYXf6CLcRCOagEL6uPZ3gW99Dpk5fhzGpcc01vR+Aq8g7xvUUnI4kKgknAUgDlviXOqYGORQPqs2WUCURFBrkyfKWUsIm7GRo2Wxif4S+t5sJJT3J/Qu96IB62ArEZZ0KhfTkHDqPp8+LbVGlklHtXtYYU0kpROO4b7JfzJNOBtGSL2p6ROyYBdjaZztvgW1QO/LKGxAMvXfWyERyahwnEclPULz23LV0FFM9nSU9tsJeT0=
  jwt:
    secure: "BU/kSi6TcdWMM2qCwG1a+lv+p7OWQNKFkGNp7rRBz6kYUzYSNC+jogiVUXVI7mRTelm55YYUEIpU+eCDQ7+oGmoUVJV+Pn9Dod167zwzcNsPwBaxuV/4oyVGfFBvk9Oj0O17sjL0uQ7GEC8ONDS/m5Dq5QQ9zyu/5j+c37yO0NCz51SXCpsPIQyPvJxjtd7l7MzLk8/BzSgkck4dVinnJtro/J4mkBtPbENAlcE8mNiF+A83/FUrBn/dp6AQJZKyFBKPOw2qVRo4VbT6yl1TK40Fe0wistibPn+BUx+ORxU1zAl1xarVK7iHNi/kMOj5BzvdVOLhgGq3UwVkDyrZKvcVnLBoCXsIgkAB+rmGX/qVrSYwGJWxvYORJ4AKVtTRBQQGCZQ7EycKuS8d+8fXYmiR7+89jg5CAUg2bf5NUNVzuH4O9eZtvdQ4uRvLSNKTlmzdH20GMD+BcN1lI5f538yoPhcAQnk05FrriAdaTqInZsSZdj1t2Yj97/TKyeEjbLHI/kBWdxZ7gZvDkU0fFVGOac02iK7XWbJKKurNTsI9SoucxZUMH2BKmlaWx0Se9zIAcWarTD4sY1Hz6CdF0IW02sgPlSbknnnBPaZ8l4toynW8PAJEqfvG7lFbOIGgzimfuR68yPZp1dyQ4C7iltFTHB5HLEBw/b4f4ZE209g="        
env:
  global:
  - BROWSER_STACK_USERNAME: xuexb1
sudo: false
cache:
  directories: node_modules
script:
- npm run test:cov
- npm run test:sauce
after_script: npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
